indent = [
  "import_declaration",
  "const_declaration",
  "var_declaration",
  "type_declaration",
  "function_declaration",
  "method_declaration",
  "composite_literal",
  "func_literal",
  "literal_value",
  "expression_case",
  "default_case",
  "argument_list",
  "block"
]

outdent = [
 "case",
 "}",
 "]",
 ")"
]
