[package]
name = "helix-view"
version = "0.1.0"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
term = ["tui", "crossterm"]
default = ["term"]

[dependencies]
anyhow = "1"
helix-core = { path = "../helix-core" }
helix-lsp = { path = "../helix-lsp"}

# Conversion traits
# tui = { version = "0.12", default-features = false, features = ["crossterm"], optional = true}
tui = { git = "https://github.com/fdehau/tui-rs", default-features = false, features = ["crossterm"], optional = true}
crossterm = { version = "0.19", features = ["event-stream"], optional = true }
once_cell = "1.4"
url = "2"

smol = "1"
futures-util = "0.3"
