[package]
name = "helix-syntax"
version = "0.1.0"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.17"
enum-iterator = "0.6"

[build-dependencies]
cc = { version = "1",  features = ["parallel"] }
