[package]
name = "helix-core"
version = "0.1.0"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
helix-syntax = { path = "../helix-syntax" }

ropey = "1.2.0"
anyhow = "1.0.31"
smallvec = "1.4.0"
tendril = { git = "https://github.com/servo/tendril" }
unicode-segmentation = "1.6.0"
unicode-width = "0.1.7"
# slab = "0.4.2"
tree-sitter = "0.16.1"
once_cell = "1.4.1"
