[package]
name = "helix-core"
version = "0.1.0"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ropey = "1.1.0"
ropey = { git = "https://github.com/cessen/ropey" }
anyhow = "1.0.31"
smallvec = "1.4.0"
tendril = { git = "https://github.com/servo/tendril" }
# slab = "0.4.2"
