[package]
name = "helix-term"
version = "0.1.0"
description = "A post-modern text editor."
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hx"
path = "src/main.rs"

[dependencies]
helix-core = { path = "../helix-core" }
helix-view = { path = "../helix-view", features = ["term"]}
helix-lsp = { path = "../helix-lsp"}

anyhow = "1"
once_cell = "1.4"

smol = "1"
smol-timeout = "0.6"
num_cpus = "1"
tui = { version = "0.15", default-features = false, features = ["crossterm"] }
crossterm = { version = "0.19", features = ["event-stream"] }
clap = { version = "3.0.0-beta.2 ", default-features = false, features = ["std", "cargo"] }

futures-util = "0.3"

# Logging
fern = "0.6"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
log = "0.4"

# File picker
fuzzy-matcher = "0.3"
ignore = "0.4"
# shellexpand = "2.1"
dirs-next = "2.0"
# markdown doc rendering
pulldown-cmark = { version = "0.8", default-features = false }

# config
toml = "0.5"

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
