[package]
name = "helix-term"
version = "0.1.0"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hx"
path = "src/main.rs"

[dependencies]
# termwiz = { git = "https://github.com/wez/wezterm", features = ["widgets"] }
# termwiz = { path = "../../wezterm/termwiz", default-features = false, features = ["widgets"] }

anyhow = "1.0.31"
argh = "0.1.3"
helix-core = { path = "../helix-core" }
# crossterm = { version = "0.17.5", features = ["event-stream"] }
crossterm = { git = "https://github.com/crossterm-rs/crossterm", branch = "mio-update", features = ["event-stream"] }

futures = { version = "0.3.5", default-features = false, features = ["std"] }
# futures-timer = "3.0.2"
smol = "0.1.10"
num_cpus = "1.13.0"
piper = "0.1.2"
# tui = { version = "0.9.5", default-features = false }
